services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.1.2
    container_name: lavalink
    restart: always
    network_mode: "host"
    environment:
      - _JAVA_OPTIONS=-Xmx4G
      - LAVALINK_SERVER_KOE_ENABLE_JDA_NAS=true 
      - LAVALINK_SERVER_NATIVE_AUDIO_TYPE=magma
    volumes:
      - ./Lavalink:/opt/Lavalink
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml

  sambot:
    build: .
    container_name: sambot
    volumes:
      - .:/app
    env_file:
      - .env
    network_mode: "host"
    environment:
      - WAVE_URI=http://127.0.0.1:2333 
    restart: unless-stopped
    depends_on:
      - lavalink